### ISSUE TITLE
Doesn't handle multiple delimiters replacement inside a same selected text + doesn't replace the exact text 

### ISSUE THREAD

**Issue by Bleety** [achyutmorang/math-delimiters-replacer-addon#5]
When a large chunk of text is selected with multiple parts with $, it doesn't do anything. 
For example : "let $\epsilon > 0$, let $f$ a continuous function ...$" will not be formatted when selected as a whole. 

In top of that, when it replace "$ math stuff $" it doesn't erase the part with $ to put \( \) at the same place. Instead it paste the selected part formatted with \( \) at the beginning of the card. Letting the part with $ at the same place it was before.

**Comment by achyutmorang** [comment]
Try pasting the text without formatting (Ctrl + Shift + V) and then select the entire text field (Ctrl + A) followed by clicking the \(...\) button.
It is pasted at the beginning because I couldn't find an alternative working solution to this.

**Comment by Bleety** [comment]
It doesn't seem to work at all. I don't understand what should I paste first ? The text i want to format ? I assume it's what you are talking about.
But still, after copying and pasting without formatting my text and selecting it and pressing the ' \\( ... \\) ' button, it still do nothing

**Comment by Bleety** [comment]
Ok I fixed it. There was a ' character in my text and when inserting the text with the '  the program thought it was the end of the text to insert, therefore creating an error. 
I fixed it by adding this line just before the creation of the javascript command :
`    modified_text = modified_text.replace("\'", "\\\'")`

**Comment by achyutmorang** [comment]
Make a pull request, i will merge it. is it working now?

**Comment by Bleety** [comment]
edit : i corrected it to adapt every possible special character by using backticks : \` \` 
And I created a pull request.  (Hope it works, never did it before...)

**Comment by achyutmorang** [comment]
learnt a cool new trick! I never thought of using backticks before.
merged it.

**Comment by achyutmorang** [comment]
> Instead it paste the selected part formatted with ( ) at the beginning of the card.

Hey I have updated the code. Check the new version. does exactly replace the selected text now. let me know if any changes required
